name: Publicar paquete
on:
  workflow_dispatch:
  #push:
  #  branches:
  #   - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        env:
            GITHUB_TOKEN: ${{secrets.AJUZ_TOKEN }}
        run: mvn deploy
